// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_plane.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceActor = `-- name: AddWorkspaceActor :exec
INSERT INTO workspace_actors (workspace_id, actor_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddWorkspaceActorParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	ActorID     int64 `json:"actor_id"`
}

func (q *Queries) AddWorkspaceActor(ctx context.Context, arg AddWorkspaceActorParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceActor, arg.WorkspaceID, arg.ActorID)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, actor_id, csrf_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	ActorID   int64              `json:"actor_id"`
	CsrfHash  []byte             `json:"csrf_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.ActorID,
		arg.CsrfHash,
		arg.ExpiresAt,
	)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT actor_id, csrf_hash
FROM sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetActiveSessionRow struct {
	ActorID  int64  `json:"actor_id"`
	CsrfHash []byte `json:"csrf_hash"`
}

func (q *Queries) GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, tokenHash)
	var i GetActiveSessionRow
	err := row.Scan(&i.ActorID, &i.CsrfHash)
	return i, err
}

const getActorByID = `-- name: GetActorByID :one
SELECT id, actor_key, role
FROM actors
WHERE id = $1
`

type GetActorByIDRow struct {
	ID       int64  `json:"id"`
	ActorKey string `json:"actor_key"`
	Role     string `json:"role"`
}

func (q *Queries) GetActorByID(ctx context.Context, id int64) (GetActorByIDRow, error) {
	row := q.db.QueryRow(ctx, getActorByID, id)
	var i GetActorByIDRow
	err := row.Scan(&i.ID, &i.ActorKey, &i.Role)
	return i, err
}

const getActorByKey = `-- name: GetActorByKey :one
SELECT id, actor_key, role, password_hash
FROM actors
WHERE actor_key = $1
`

type GetActorByKeyRow struct {
	ID           int64  `json:"id"`
	ActorKey     string `json:"actor_key"`
	Role         string `json:"role"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetActorByKey(ctx context.Context, actorKey string) (GetActorByKeyRow, error) {
	row := q.db.QueryRow(ctx, getActorByKey, actorKey)
	var i GetActorByKeyRow
	err := row.Scan(
		&i.ID,
		&i.ActorKey,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, public_id, name, namespace_name
FROM workspaces
WHERE id = $1
`

type GetWorkspaceByIDRow struct {
	ID            int64  `json:"id"`
	PublicID      string `json:"public_id"`
	Name          string `json:"name"`
	NamespaceName string `json:"namespace_name"`
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (GetWorkspaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i GetWorkspaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.NamespaceName,
	)
	return i, err
}

const getWorkspaceForActor = `-- name: GetWorkspaceForActor :one
SELECT w.id, w.public_id, w.name, w.namespace_name
FROM workspaces AS w
JOIN workspace_actors AS wa ON wa.workspace_id = w.id
WHERE wa.actor_id = $1
ORDER BY w.id
LIMIT 1
`

type GetWorkspaceForActorRow struct {
	ID            int64  `json:"id"`
	PublicID      string `json:"public_id"`
	Name          string `json:"name"`
	NamespaceName string `json:"namespace_name"`
}

func (q *Queries) GetWorkspaceForActor(ctx context.Context, actorID int64) (GetWorkspaceForActorRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForActor, actorID)
	var i GetWorkspaceForActorRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.NamespaceName,
	)
	return i, err
}

const revokeActiveSession = `-- name: RevokeActiveSession :execrows
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
  AND actor_id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
`

type RevokeActiveSessionParams struct {
	TokenHash []byte `json:"token_hash"`
	ActorID   int64  `json:"actor_id"`
}

func (q *Queries) RevokeActiveSession(ctx context.Context, arg RevokeActiveSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveSession, arg.TokenHash, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const upsertActor = `-- name: UpsertActor :one
INSERT INTO actors (actor_key, role, password_hash)
VALUES ($1, $2, $3)
ON CONFLICT (actor_key) DO UPDATE
SET role = EXCLUDED.role,
    password_hash = EXCLUDED.password_hash
RETURNING id
`

type UpsertActorParams struct {
	ActorKey     string `json:"actor_key"`
	Role         string `json:"role"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpsertActor(ctx context.Context, arg UpsertActorParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertActor, arg.ActorKey, arg.Role, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (public_id, name, namespace_name)
VALUES ($1, $2, $3)
ON CONFLICT (namespace_name) DO UPDATE
SET name = EXCLUDED.name
RETURNING id
`

type UpsertWorkspaceParams struct {
	PublicID      string `json:"public_id"`
	Name          string `json:"name"`
	NamespaceName string `json:"namespace_name"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace, arg.PublicID, arg.Name, arg.NamespaceName)
	var id int64
	err := row.Scan(&id)
	return id, err
}
