// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_plane.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveApp = `-- name: ArchiveApp :one
UPDATE apps a
SET archived_at = now(), version = a.version + 1, updated_at = now()
FROM projects p
WHERE a.project_id = p.id AND p.workspace_id = $1 AND p.public_id = $2
  AND a.public_id = $3 AND a.version = $4 AND a.archived_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM app_environments ae WHERE ae.app_id = a.id AND ae.archived_at IS NULL)
RETURNING a.id, a.public_id, a.project_id, a.name, a.version, a.created_at, a.updated_at, a.archived_at
`

type ArchiveAppParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	PublicID_2  string `json:"public_id_2"`
	Version     int64  `json:"version"`
}

type ArchiveAppRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ArchiveApp(ctx context.Context, arg ArchiveAppParams) (ArchiveAppRow, error) {
	row := q.db.QueryRow(ctx, archiveApp,
		arg.WorkspaceID,
		arg.PublicID,
		arg.PublicID_2,
		arg.Version,
	)
	var i ArchiveAppRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const archiveEnvironment = `-- name: ArchiveEnvironment :one
UPDATE environments e
SET archived_at = now(), version = e.version + 1, updated_at = now()
FROM projects p
WHERE e.project_id = p.id AND p.workspace_id = $1 AND p.public_id = $2
  AND e.public_id = $3 AND e.version = $4 AND e.archived_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM app_environments ae WHERE ae.environment_id = e.id AND ae.archived_at IS NULL)
RETURNING e.id, e.public_id, e.project_id, e.name, e.version, e.created_at, e.updated_at, e.archived_at
`

type ArchiveEnvironmentParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	PublicID_2  string `json:"public_id_2"`
	Version     int64  `json:"version"`
}

type ArchiveEnvironmentRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ArchiveEnvironment(ctx context.Context, arg ArchiveEnvironmentParams) (ArchiveEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, archiveEnvironment,
		arg.WorkspaceID,
		arg.PublicID,
		arg.PublicID_2,
		arg.Version,
	)
	var i ArchiveEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const archiveProject = `-- name: ArchiveProject :one
UPDATE projects p
SET archived_at = now(), version = version + 1, updated_at = now()
WHERE p.workspace_id = $1 AND p.public_id = $2 AND p.version = $3 AND p.archived_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM environments e WHERE e.project_id = p.id AND e.archived_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM apps a WHERE a.project_id = p.id AND a.archived_at IS NULL)
RETURNING p.id, p.public_id, p.workspace_id, p.name, p.version, p.created_at, p.updated_at, p.archived_at
`

type ArchiveProjectParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	Version     int64  `json:"version"`
}

type ArchiveProjectRow struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (ArchiveProjectRow, error) {
	row := q.db.QueryRow(ctx, archiveProject, arg.WorkspaceID, arg.PublicID, arg.Version)
	var i ArchiveProjectRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WorkspaceID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps(public_id, project_id, name, name_key)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, project_id, name, version, created_at, updated_at, archived_at
`

type CreateAppParams struct {
	PublicID  string `json:"public_id"`
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
	NameKey   string `json:"name_key"`
}

type CreateAppRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (CreateAppRow, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.PublicID,
		arg.ProjectID,
		arg.Name,
		arg.NameKey,
	)
	var i CreateAppRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments(public_id, project_id, name, name_key)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, project_id, name, version, created_at, updated_at, archived_at
`

type CreateEnvironmentParams struct {
	PublicID  string `json:"public_id"`
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
	NameKey   string `json:"name_key"`
}

type CreateEnvironmentRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (CreateEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.PublicID,
		arg.ProjectID,
		arg.Name,
		arg.NameKey,
	)
	var i CreateEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects(public_id, workspace_id, name, name_key)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, workspace_id, name, version, created_at, updated_at, archived_at
`

type CreateProjectParams struct {
	PublicID    string `json:"public_id"`
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
	NameKey     string `json:"name_key"`
}

type CreateProjectRow struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.PublicID,
		arg.WorkspaceID,
		arg.Name,
		arg.NameKey,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WorkspaceID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findActiveAppForUpdate = `-- name: FindActiveAppForUpdate :one
SELECT a.id, a.public_id, a.project_id, a.name, a.version, a.created_at, a.updated_at, a.archived_at
FROM apps a
JOIN projects p ON p.id = a.project_id
WHERE p.workspace_id = $1 AND p.public_id = $2 AND a.public_id = $3 AND a.archived_at IS NULL
FOR UPDATE OF a
`

type FindActiveAppForUpdateParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	PublicID_2  string `json:"public_id_2"`
}

type FindActiveAppForUpdateRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) FindActiveAppForUpdate(ctx context.Context, arg FindActiveAppForUpdateParams) (FindActiveAppForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findActiveAppForUpdate, arg.WorkspaceID, arg.PublicID, arg.PublicID_2)
	var i FindActiveAppForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findActiveEnvironmentForUpdate = `-- name: FindActiveEnvironmentForUpdate :one
SELECT e.id, e.public_id, e.project_id, e.name, e.version, e.created_at, e.updated_at, e.archived_at
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE p.workspace_id = $1 AND p.public_id = $2 AND e.public_id = $3 AND e.archived_at IS NULL
FOR UPDATE OF e
`

type FindActiveEnvironmentForUpdateParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	PublicID_2  string `json:"public_id_2"`
}

type FindActiveEnvironmentForUpdateRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) FindActiveEnvironmentForUpdate(ctx context.Context, arg FindActiveEnvironmentForUpdateParams) (FindActiveEnvironmentForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findActiveEnvironmentForUpdate, arg.WorkspaceID, arg.PublicID, arg.PublicID_2)
	var i FindActiveEnvironmentForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findActiveProjectForUpdate = `-- name: FindActiveProjectForUpdate :one
SELECT id, public_id, workspace_id, name, version, created_at, updated_at, archived_at
FROM projects
WHERE workspace_id = $1 AND public_id = $2 AND archived_at IS NULL
FOR UPDATE
`

type FindActiveProjectForUpdateParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
}

type FindActiveProjectForUpdateRow struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) FindActiveProjectForUpdate(ctx context.Context, arg FindActiveProjectForUpdateParams) (FindActiveProjectForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findActiveProjectForUpdate, arg.WorkspaceID, arg.PublicID)
	var i FindActiveProjectForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WorkspaceID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findApp = `-- name: FindApp :one
SELECT a.id, a.public_id, a.project_id, a.name, a.version, a.created_at, a.updated_at, a.archived_at
FROM apps a
JOIN projects p ON p.id = a.project_id
WHERE p.workspace_id = $1 AND p.public_id = $2 AND a.public_id = $3
`

type FindAppParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	PublicID_2  string `json:"public_id_2"`
}

type FindAppRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) FindApp(ctx context.Context, arg FindAppParams) (FindAppRow, error) {
	row := q.db.QueryRow(ctx, findApp, arg.WorkspaceID, arg.PublicID, arg.PublicID_2)
	var i FindAppRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findEnvironment = `-- name: FindEnvironment :one
SELECT e.id, e.public_id, e.project_id, e.name, e.version, e.created_at, e.updated_at, e.archived_at
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE p.workspace_id = $1 AND p.public_id = $2 AND e.public_id = $3
`

type FindEnvironmentParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	PublicID_2  string `json:"public_id_2"`
}

type FindEnvironmentRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) FindEnvironment(ctx context.Context, arg FindEnvironmentParams) (FindEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, findEnvironment, arg.WorkspaceID, arg.PublicID, arg.PublicID_2)
	var i FindEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findProject = `-- name: FindProject :one
SELECT id, public_id, workspace_id, name, version, created_at, updated_at, archived_at
FROM projects
WHERE workspace_id = $1 AND public_id = $2
`

type FindProjectParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
}

type FindProjectRow struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) FindProject(ctx context.Context, arg FindProjectParams) (FindProjectRow, error) {
	row := q.db.QueryRow(ctx, findProject, arg.WorkspaceID, arg.PublicID)
	var i FindProjectRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WorkspaceID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findWorkspaceForUser = `-- name: FindWorkspaceForUser :one
SELECT w.id, w.public_id, w.name, w.namespace_name, w.version, w.bootstrap_state, w.created_at, w.updated_at
FROM workspaces AS w
JOIN workspace_memberships AS wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1 AND wm.status = 'Active' AND w.public_id = $2
`

type FindWorkspaceForUserParams struct {
	UserID   int64  `json:"user_id"`
	PublicID string `json:"public_id"`
}

type FindWorkspaceForUserRow struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	Version        int64              `json:"version"`
	BootstrapState string             `json:"bootstrap_state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindWorkspaceForUser(ctx context.Context, arg FindWorkspaceForUserParams) (FindWorkspaceForUserRow, error) {
	row := q.db.QueryRow(ctx, findWorkspaceForUser, arg.UserID, arg.PublicID)
	var i FindWorkspaceForUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.NamespaceName,
		&i.Version,
		&i.BootstrapState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkspaceOperationByIdempotency = `-- name: FindWorkspaceOperationByIdempotency :one
SELECT o.id, o.public_id, o.workspace_id, COALESCE(o.requested_by_user_id,0)::bigint AS actor_id, o.kind, o.status,
       o.desired_version, o.attempts, o.created_at, o.updated_at,
       o.error_code, o.error_message, o.payload_hash
FROM operations o
WHERE o.requested_by_user_id = CAST($1 AS bigint)
  AND o.kind = 'EnsureWorkspace'
  AND o.app_environment_id IS NULL
  AND o.deployment_id IS NULL
  AND o.idempotency_hash = $2
`

type FindWorkspaceOperationByIdempotencyParams struct {
	RequestedByUserID int64  `json:"requested_by_user_id"`
	IdempotencyHash   []byte `json:"idempotency_hash"`
}

type FindWorkspaceOperationByIdempotencyRow struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	WorkspaceID    int64              `json:"workspace_id"`
	ActorID        int64              `json:"actor_id"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	DesiredVersion int64              `json:"desired_version"`
	Attempts       int32              `json:"attempts"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ErrorCode      string             `json:"error_code"`
	ErrorMessage   string             `json:"error_message"`
	PayloadHash    []byte             `json:"payload_hash"`
}

func (q *Queries) FindWorkspaceOperationByIdempotency(ctx context.Context, arg FindWorkspaceOperationByIdempotencyParams) (FindWorkspaceOperationByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, findWorkspaceOperationByIdempotency, arg.RequestedByUserID, arg.IdempotencyHash)
	var i FindWorkspaceOperationByIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.Kind,
		&i.Status,
		&i.DesiredVersion,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.PayloadHash,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, public_id, name, namespace_name, version, bootstrap_state, created_at, updated_at
FROM workspaces
WHERE id = $1
`

type GetWorkspaceByIDRow struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	Version        int64              `json:"version"`
	BootstrapState string             `json:"bootstrap_state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (GetWorkspaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i GetWorkspaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.NamespaceName,
		&i.Version,
		&i.BootstrapState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceForUser = `-- name: GetWorkspaceForUser :one
SELECT w.id, w.public_id, w.name, w.namespace_name, w.version, w.bootstrap_state, w.created_at, w.updated_at
FROM workspaces AS w
JOIN workspace_memberships AS wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1 AND wm.status = 'Active'
ORDER BY w.id
LIMIT 1
`

type GetWorkspaceForUserRow struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	Version        int64              `json:"version"`
	BootstrapState string             `json:"bootstrap_state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceForUser(ctx context.Context, userID int64) (GetWorkspaceForUserRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForUser, userID)
	var i GetWorkspaceForUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.NamespaceName,
		&i.Version,
		&i.BootstrapState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspace = `-- name: InsertWorkspace :one
INSERT INTO workspaces(public_id, name, namespace_name)
VALUES ($1, $2, $3)
RETURNING id, public_id, name, namespace_name, version, bootstrap_state, created_at, updated_at
`

type InsertWorkspaceParams struct {
	PublicID      string `json:"public_id"`
	Name          string `json:"name"`
	NamespaceName string `json:"namespace_name"`
}

type InsertWorkspaceRow struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	Version        int64              `json:"version"`
	BootstrapState string             `json:"bootstrap_state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (InsertWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, insertWorkspace, arg.PublicID, arg.Name, arg.NamespaceName)
	var i InsertWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.NamespaceName,
		&i.Version,
		&i.BootstrapState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspaceOperation = `-- name: InsertWorkspaceOperation :one
INSERT INTO operations(
    public_id, workspace_id, app_environment_id, deployment_id, requested_by_user_id, kind, status, agent_installation_id,
    idempotency_hash, payload_hash, desired_version
)
VALUES ($1, $2, NULL, NULL, CAST($3 AS bigint),
        'EnsureWorkspace', 'Pending', $4, $5, $6, 1)
RETURNING id, public_id, workspace_id, COALESCE(requested_by_user_id,0)::bigint AS actor_id, kind, status,
          desired_version, attempts, created_at, updated_at, error_code, error_message
`

type InsertWorkspaceOperationParams struct {
	PublicID            string      `json:"public_id"`
	WorkspaceID         int64       `json:"workspace_id"`
	RequestedByUserID   int64       `json:"requested_by_user_id"`
	AgentInstallationID pgtype.Int8 `json:"agent_installation_id"`
	IdempotencyHash     []byte      `json:"idempotency_hash"`
	PayloadHash         []byte      `json:"payload_hash"`
}

type InsertWorkspaceOperationRow struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	WorkspaceID    int64              `json:"workspace_id"`
	ActorID        int64              `json:"actor_id"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	DesiredVersion int64              `json:"desired_version"`
	Attempts       int32              `json:"attempts"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ErrorCode      string             `json:"error_code"`
	ErrorMessage   string             `json:"error_message"`
}

func (q *Queries) InsertWorkspaceOperation(ctx context.Context, arg InsertWorkspaceOperationParams) (InsertWorkspaceOperationRow, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceOperation,
		arg.PublicID,
		arg.WorkspaceID,
		arg.RequestedByUserID,
		arg.AgentInstallationID,
		arg.IdempotencyHash,
		arg.PayloadHash,
	)
	var i InsertWorkspaceOperationRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.Kind,
		&i.Status,
		&i.DesiredVersion,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT a.id, a.public_id, a.project_id, a.name, a.version, a.created_at, a.updated_at, a.archived_at
FROM apps a
JOIN projects p ON p.id = a.project_id
WHERE p.workspace_id = $1 AND p.public_id = $2
  AND a.id < $3
  AND ($5::boolean OR a.archived_at IS NULL)
ORDER BY a.id DESC
LIMIT $4
`

type ListAppsParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	ID          int64  `json:"id"`
	Limit       int32  `json:"limit"`
	Column5     bool   `json:"column_5"`
}

type ListAppsRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ListApps(ctx context.Context, arg ListAppsParams) ([]ListAppsRow, error) {
	rows, err := q.db.Query(ctx, listApps,
		arg.WorkspaceID,
		arg.PublicID,
		arg.ID,
		arg.Limit,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsRow{}
	for rows.Next() {
		var i ListAppsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ProjectID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT e.id, e.public_id, e.project_id, e.name, e.version, e.created_at, e.updated_at, e.archived_at
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE p.workspace_id = $1 AND p.public_id = $2
  AND e.id < $3
  AND ($5::boolean OR e.archived_at IS NULL)
ORDER BY e.id DESC
LIMIT $4
`

type ListEnvironmentsParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	ID          int64  `json:"id"`
	Limit       int32  `json:"limit"`
	Column5     bool   `json:"column_5"`
}

type ListEnvironmentsRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ListEnvironments(ctx context.Context, arg ListEnvironmentsParams) ([]ListEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironments,
		arg.WorkspaceID,
		arg.PublicID,
		arg.ID,
		arg.Limit,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsRow{}
	for rows.Next() {
		var i ListEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ProjectID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, public_id, workspace_id, name, version, created_at, updated_at, archived_at
FROM projects
WHERE workspace_id = $1
  AND id < $2
  AND ($4::boolean OR archived_at IS NULL)
ORDER BY id DESC
LIMIT $3
`

type ListProjectsParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	ID          int64 `json:"id"`
	Limit       int32 `json:"limit"`
	Column4     bool  `json:"column_4"`
}

type ListProjectsRow struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.WorkspaceID,
		arg.ID,
		arg.Limit,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.WorkspaceID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.public_id, w.name, w.namespace_name, w.version, w.bootstrap_state, w.created_at, w.updated_at
FROM workspaces AS w
JOIN workspace_memberships AS wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1 AND wm.status = 'Active' AND w.id < $2
ORDER BY w.id DESC
LIMIT $3
`

type ListWorkspacesForUserParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
}

type ListWorkspacesForUserRow struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	Version        int64              `json:"version"`
	BootstrapState string             `json:"bootstrap_state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, arg ListWorkspacesForUserParams) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.NamespaceName,
			&i.Version,
			&i.BootstrapState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :one
UPDATE apps a
SET name = $5, name_key = $6, version = a.version + 1, updated_at = now()
FROM projects p
WHERE a.project_id = p.id AND p.workspace_id = $1 AND p.public_id = $2
  AND a.public_id = $3 AND a.version = $4 AND a.archived_at IS NULL
RETURNING a.id, a.public_id, a.project_id, a.name, a.version, a.created_at, a.updated_at, a.archived_at
`

type UpdateAppParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	PublicID_2  string `json:"public_id_2"`
	Version     int64  `json:"version"`
	Name        string `json:"name"`
	NameKey     string `json:"name_key"`
}

type UpdateAppRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (UpdateAppRow, error) {
	row := q.db.QueryRow(ctx, updateApp,
		arg.WorkspaceID,
		arg.PublicID,
		arg.PublicID_2,
		arg.Version,
		arg.Name,
		arg.NameKey,
	)
	var i UpdateAppRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments e
SET name = $5, name_key = $6, version = e.version + 1, updated_at = now()
FROM projects p
WHERE e.project_id = p.id AND p.workspace_id = $1 AND p.public_id = $2
  AND e.public_id = $3 AND e.version = $4 AND e.archived_at IS NULL
RETURNING e.id, e.public_id, e.project_id, e.name, e.version, e.created_at, e.updated_at, e.archived_at
`

type UpdateEnvironmentParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	PublicID_2  string `json:"public_id_2"`
	Version     int64  `json:"version"`
	Name        string `json:"name"`
	NameKey     string `json:"name_key"`
}

type UpdateEnvironmentRow struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (UpdateEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, updateEnvironment,
		arg.WorkspaceID,
		arg.PublicID,
		arg.PublicID_2,
		arg.Version,
		arg.Name,
		arg.NameKey,
	)
	var i UpdateEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $4, name_key = $5, version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND public_id = $2 AND version = $3 AND archived_at IS NULL
RETURNING id, public_id, workspace_id, name, version, created_at, updated_at, archived_at
`

type UpdateProjectParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	PublicID    string `json:"public_id"`
	Version     int64  `json:"version"`
	Name        string `json:"name"`
	NameKey     string `json:"name_key"`
}

type UpdateProjectRow struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.WorkspaceID,
		arg.PublicID,
		arg.Version,
		arg.Name,
		arg.NameKey,
	)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WorkspaceID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :one
UPDATE workspaces
SET name = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2
RETURNING id, public_id, name, namespace_name, version, bootstrap_state, created_at, updated_at
`

type UpdateWorkspaceNameParams struct {
	ID      int64  `json:"id"`
	Version int64  `json:"version"`
	Name    string `json:"name"`
}

type UpdateWorkspaceNameRow struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	Version        int64              `json:"version"`
	BootstrapState string             `json:"bootstrap_state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (UpdateWorkspaceNameRow, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceName, arg.ID, arg.Version, arg.Name)
	var i UpdateWorkspaceNameRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.NamespaceName,
		&i.Version,
		&i.BootstrapState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (public_id, name, namespace_name)
VALUES ($1, $2, $3)
ON CONFLICT (namespace_name) DO UPDATE
SET name = EXCLUDED.name
RETURNING id
`

type UpsertWorkspaceParams struct {
	PublicID      string `json:"public_id"`
	Name          string `json:"name"`
	NamespaceName string `json:"namespace_name"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace, arg.PublicID, arg.Name, arg.NamespaceName)
	var id int64
	err := row.Scan(&id)
	return id, err
}
