// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Actor struct {
	ID           int64              `json:"id"`
	ActorKey     string             `json:"actor_key"`
	Role         string             `json:"role"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Deployment struct {
	ID                  int64              `json:"id"`
	PublicID            string             `json:"public_id"`
	WorkspaceID         int64              `json:"workspace_id"`
	Name                string             `json:"name"`
	Slug                pgtype.Text        `json:"slug"`
	IntentJson          []byte             `json:"intent_json"`
	DesiredVersion      int64              `json:"desired_version"`
	ObservedVersion     int64              `json:"observed_version"`
	ObservedRelease     string             `json:"observed_release"`
	LastState           string             `json:"last_state"`
	LastMessage         string             `json:"last_message"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	RuntimeName         string             `json:"runtime_name"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
}

type Operation struct {
	ID              int64              `json:"id"`
	PublicID        string             `json:"public_id"`
	WorkspaceID     int64              `json:"workspace_id"`
	DeploymentID    pgtype.Int8        `json:"deployment_id"`
	ActorID         int64              `json:"actor_id"`
	Kind            string             `json:"kind"`
	Status          string             `json:"status"`
	IdempotencyHash []byte             `json:"idempotency_hash"`
	PayloadHash     []byte             `json:"payload_hash"`
	IntentJson      []byte             `json:"intent_json"`
	DesiredVersion  int64              `json:"desired_version"`
	Sequence        int64              `json:"sequence"`
	Attempts        int32              `json:"attempts"`
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseUntil      pgtype.Timestamptz `json:"lease_until"`
	WorkerID        pgtype.Text        `json:"worker_id"`
	FencingToken    int64              `json:"fencing_token"`
	ErrorCode       string             `json:"error_code"`
	ErrorMessage    string             `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	TokenHash []byte             `json:"token_hash"`
	ActorID   int64              `json:"actor_id"`
	CsrfHash  []byte             `json:"csrf_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	BootstrapState string             `json:"bootstrap_state"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceActor struct {
	WorkspaceID int64 `json:"workspace_id"`
	ActorID     int64 `json:"actor_id"`
}
