// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Actor struct {
	ID           int64              `json:"id"`
	ActorKey     string             `json:"actor_key"`
	Role         string             `json:"role"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type App struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	NameKey    string             `json:"name_key"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type AppEnvironment struct {
	ID                   int64              `json:"id"`
	PublicID             string             `json:"public_id"`
	WorkspaceID          int64              `json:"workspace_id"`
	ProjectID            int64              `json:"project_id"`
	AppID                int64              `json:"app_id"`
	EnvironmentID        int64              `json:"environment_id"`
	SourceBranch         string             `json:"source_branch"`
	RuntimeName          string             `json:"runtime_name"`
	ConfigurationJson    []byte             `json:"configuration_json"`
	ConfigurationVersion int64              `json:"configuration_version"`
	Version              int64              `json:"version"`
	DesiredDeploymentID  pgtype.Int8        `json:"desired_deployment_id"`
	CurrentDeploymentID  pgtype.Int8        `json:"current_deployment_id"`
	CurrentReleaseID     pgtype.Int8        `json:"current_release_id"`
	LastState            string             `json:"last_state"`
	LastMessage          string             `json:"last_message"`
	DeletionRequestedAt  pgtype.Timestamptz `json:"deletion_requested_at"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AppGithubSource struct {
	AppID                int64              `json:"app_id"`
	GithubInstallationID int64              `json:"github_installation_id"`
	RepositoryID         int64              `json:"repository_id"`
	RepositoryName       string             `json:"repository_name"`
	RepositoryFullName   string             `json:"repository_full_name"`
	RepositoryPrivate    bool               `json:"repository_private"`
	DefaultBranch        string             `json:"default_branch"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Build struct {
	ID                           int64              `json:"id"`
	PublicID                     string             `json:"public_id"`
	WorkspaceID                  int64              `json:"workspace_id"`
	ProjectID                    int64              `json:"project_id"`
	AppID                        int64              `json:"app_id"`
	RequestedByActorID           int64              `json:"requested_by_actor_id"`
	GithubInstallationID         pgtype.Int8        `json:"github_installation_id"`
	GithubInstallationExternalID int64              `json:"github_installation_external_id"`
	RepositoryID                 int64              `json:"repository_id"`
	RepositoryFullName           string             `json:"repository_full_name"`
	CommitSha                    string             `json:"commit_sha"`
	Platform                     string             `json:"platform"`
	Status                       string             `json:"status"`
	Attempts                     int32              `json:"attempts"`
	WorkerID                     pgtype.Text        `json:"worker_id"`
	FencingToken                 int64              `json:"fencing_token"`
	LeaseUntil                   pgtype.Timestamptz `json:"lease_until"`
	IdempotencyHash              []byte             `json:"idempotency_hash"`
	PayloadHash                  []byte             `json:"payload_hash"`
	ErrorCode                    pgtype.Text        `json:"error_code"`
	ErrorMessage                 pgtype.Text        `json:"error_message"`
	StartedAt                    pgtype.Timestamptz `json:"started_at"`
	CompletedAt                  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	SourceBranch                 string             `json:"source_branch"`
	AppEnvironmentID             int64              `json:"app_environment_id"`
}

type BuildLog struct {
	BuildID   int64              `json:"build_id"`
	Sequence  int64              `json:"sequence"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Deployment struct {
	ID                   int64              `json:"id"`
	PublicID             string             `json:"public_id"`
	WorkspaceID          int64              `json:"workspace_id"`
	AppEnvironmentID     int64              `json:"app_environment_id"`
	AppID                int64              `json:"app_id"`
	ReleaseID            int64              `json:"release_id"`
	RequestedByActorID   int64              `json:"requested_by_actor_id"`
	ConfigurationVersion int64              `json:"configuration_version"`
	ConfigurationJson    []byte             `json:"configuration_json"`
	Status               string             `json:"status"`
	Message              string             `json:"message"`
	ObservedRelease      string             `json:"observed_release"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Environment struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	NameKey    string             `json:"name_key"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type GithubConnectionState struct {
	ID                   int64              `json:"id"`
	StateHash            []byte             `json:"state_hash"`
	BrowserHash          []byte             `json:"browser_hash"`
	ActorID              int64              `json:"actor_id"`
	WorkspaceID          int64              `json:"workspace_id"`
	Step                 string             `json:"step"`
	GithubInstallationID pgtype.Int8        `json:"github_installation_id"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type GithubInstallation struct {
	ID                   int64              `json:"id"`
	PublicID             string             `json:"public_id"`
	WorkspaceID          int64              `json:"workspace_id"`
	ConnectedByActorID   int64              `json:"connected_by_actor_id"`
	GithubInstallationID int64              `json:"github_installation_id"`
	AccountID            int64              `json:"account_id"`
	AccountLogin         string             `json:"account_login"`
	AccountType          string             `json:"account_type"`
	RepositorySelection  string             `json:"repository_selection"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Operation struct {
	ID               int64              `json:"id"`
	PublicID         string             `json:"public_id"`
	WorkspaceID      int64              `json:"workspace_id"`
	AppEnvironmentID pgtype.Int8        `json:"app_environment_id"`
	DeploymentID     pgtype.Int8        `json:"deployment_id"`
	ActorID          int64              `json:"actor_id"`
	Kind             string             `json:"kind"`
	Status           string             `json:"status"`
	IdempotencyHash  []byte             `json:"idempotency_hash"`
	PayloadHash      []byte             `json:"payload_hash"`
	DesiredVersion   int64              `json:"desired_version"`
	Attempts         int32              `json:"attempts"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseUntil       pgtype.Timestamptz `json:"lease_until"`
	WorkerID         pgtype.Text        `json:"worker_id"`
	FencingToken     int64              `json:"fencing_token"`
	ErrorCode        string             `json:"error_code"`
	ErrorMessage     string             `json:"error_message"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Parameter struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	WorkspaceID    int64              `json:"workspace_id"`
	Path           string             `json:"path"`
	Kind           string             `json:"kind"`
	Description    string             `json:"description"`
	CurrentVersion int64              `json:"current_version"`
	Version        int64              `json:"version"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ParameterVersion struct {
	ParameterID          int64              `json:"parameter_id"`
	Version              int64              `json:"version"`
	CreatedByActorID     int64              `json:"created_by_actor_id"`
	PlaintextValue       pgtype.Text        `json:"plaintext_value"`
	SecretReference      pgtype.Text        `json:"secret_reference"`
	SecretBackendVersion pgtype.Int8        `json:"secret_backend_version"`
	Fingerprint          []byte             `json:"fingerprint"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	NameKey     string             `json:"name_key"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

type Release struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	ProjectID   int64              `json:"project_id"`
	AppID       int64              `json:"app_id"`
	BuildID     int64              `json:"build_id"`
	CommitSha   string             `json:"commit_sha"`
	Image       string             `json:"image"`
	Platform    string             `json:"platform"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	TokenHash []byte             `json:"token_hash"`
	ActorID   int64              `json:"actor_id"`
	CsrfHash  []byte             `json:"csrf_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	BootstrapState string             `json:"bootstrap_state"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Version        int64              `json:"version"`
}

type WorkspaceActor struct {
	WorkspaceID int64 `json:"workspace_id"`
	ActorID     int64 `json:"actor_id"`
}
