// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessGrant struct {
	ID               int64              `json:"id"`
	PublicID         string             `json:"public_id"`
	WorkspaceID      int64              `json:"workspace_id"`
	SubjectType      string             `json:"subject_type"`
	SubjectID        int64              `json:"subject_id"`
	ResourceType     string             `json:"resource_type"`
	ResourcePublicID string             `json:"resource_public_id"`
	Relation         string             `json:"relation"`
	Version          int64              `json:"version"`
	CreatedByUserID  int64              `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type App struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	NameKey    string             `json:"name_key"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type AppEnvironment struct {
	ID                   int64              `json:"id"`
	PublicID             string             `json:"public_id"`
	WorkspaceID          int64              `json:"workspace_id"`
	ProjectID            int64              `json:"project_id"`
	AppID                int64              `json:"app_id"`
	EnvironmentID        int64              `json:"environment_id"`
	SourceBranch         string             `json:"source_branch"`
	RuntimeName          string             `json:"runtime_name"`
	ConfigurationJson    []byte             `json:"configuration_json"`
	ConfigurationVersion int64              `json:"configuration_version"`
	Version              int64              `json:"version"`
	DesiredDeploymentID  pgtype.Int8        `json:"desired_deployment_id"`
	CurrentDeploymentID  pgtype.Int8        `json:"current_deployment_id"`
	CurrentReleaseID     pgtype.Int8        `json:"current_release_id"`
	LastState            string             `json:"last_state"`
	LastMessage          string             `json:"last_message"`
	DeletionRequestedAt  pgtype.Timestamptz `json:"deletion_requested_at"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	WorkloadKind         string             `json:"workload_kind"`
}

type AppEnvironmentConfigurationRevision struct {
	AppEnvironmentID  int64              `json:"app_environment_id"`
	Version           int64              `json:"version"`
	ConfigurationJson []byte             `json:"configuration_json"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AppEnvironmentDeliveryPolicy struct {
	AppEnvironmentID int64              `json:"app_environment_id"`
	WorkspaceID      int64              `json:"workspace_id"`
	PushEnabled      bool               `json:"push_enabled"`
	ReleaseEnabled   bool               `json:"release_enabled"`
	Version          int64              `json:"version"`
	UpdatedByUserID  int64              `json:"updated_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AppEnvironmentParameterBinding struct {
	AppEnvironmentID int64              `json:"app_environment_id"`
	EnvironmentName  string             `json:"environment_name"`
	ParameterID      int64              `json:"parameter_id"`
	ParameterVersion int64              `json:"parameter_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type AppGithubSource struct {
	AppID                int64              `json:"app_id"`
	GithubInstallationID int64              `json:"github_installation_id"`
	RepositoryID         int64              `json:"repository_id"`
	RepositoryName       string             `json:"repository_name"`
	RepositoryFullName   string             `json:"repository_full_name"`
	RepositoryPrivate    bool               `json:"repository_private"`
	DefaultBranch        string             `json:"default_branch"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AppVolume struct {
	ID                  int64              `json:"id"`
	PublicID            string             `json:"public_id"`
	WorkspaceID         int64              `json:"workspace_id"`
	AppEnvironmentID    int64              `json:"app_environment_id"`
	StorageProfileID    string             `json:"storage_profile_id"`
	RequestedSizeGib    int64              `json:"requested_size_gib"`
	ObservedSizeGib     int64              `json:"observed_size_gib"`
	MountPath           string             `json:"mount_path"`
	RetentionPolicy     string             `json:"retention_policy"`
	DesiredState        string             `json:"desired_state"`
	ObservedState       string             `json:"observed_state"`
	Message             string             `json:"message"`
	Version             int64              `json:"version"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	ActorUserID    pgtype.Int8        `json:"actor_user_id"`
	SessionID      pgtype.Int8        `json:"session_id"`
	WorkspaceID    pgtype.Int8        `json:"workspace_id"`
	Action         string             `json:"action"`
	TargetType     string             `json:"target_type"`
	TargetPublicID string             `json:"target_public_id"`
	Outcome        string             `json:"outcome"`
	Reason         string             `json:"reason"`
	RequestID      string             `json:"request_id"`
	TraceID        string             `json:"trace_id"`
	SourceHash     []byte             `json:"source_hash"`
	UserAgentHash  []byte             `json:"user_agent_hash"`
	MetadataJson   []byte             `json:"metadata_json"`
}

type AuthenticationChallenge struct {
	ID            int64              `json:"id"`
	ChallengeHash []byte             `json:"challenge_hash"`
	UserID        int64              `json:"user_id"`
	Kind          string             `json:"kind"`
	PayloadJson   []byte             `json:"payload_json"`
	Attempts      int32              `json:"attempts"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuthenticationRateLimit struct {
	KeyHash      []byte             `json:"key_hash"`
	Failures     int32              `json:"failures"`
	BlockedUntil pgtype.Timestamptz `json:"blocked_until"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Build struct {
	ID                           int64              `json:"id"`
	PublicID                     string             `json:"public_id"`
	WorkspaceID                  int64              `json:"workspace_id"`
	ProjectID                    int64              `json:"project_id"`
	AppID                        int64              `json:"app_id"`
	RequestedByUserID            int64              `json:"requested_by_user_id"`
	GithubInstallationID         pgtype.Int8        `json:"github_installation_id"`
	GithubInstallationExternalID int64              `json:"github_installation_external_id"`
	RepositoryID                 int64              `json:"repository_id"`
	RepositoryFullName           string             `json:"repository_full_name"`
	CommitSha                    string             `json:"commit_sha"`
	Platform                     string             `json:"platform"`
	Status                       string             `json:"status"`
	Attempts                     int32              `json:"attempts"`
	WorkerID                     pgtype.Text        `json:"worker_id"`
	FencingToken                 int64              `json:"fencing_token"`
	LeaseUntil                   pgtype.Timestamptz `json:"lease_until"`
	IdempotencyHash              []byte             `json:"idempotency_hash"`
	PayloadHash                  []byte             `json:"payload_hash"`
	ErrorCode                    pgtype.Text        `json:"error_code"`
	ErrorMessage                 pgtype.Text        `json:"error_message"`
	StartedAt                    pgtype.Timestamptz `json:"started_at"`
	CompletedAt                  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	SourceBranch                 string             `json:"source_branch"`
	AppEnvironmentID             int64              `json:"app_environment_id"`
	TriggerType                  string             `json:"trigger_type"`
	GithubDeliveryID             pgtype.Int8        `json:"github_delivery_id"`
	CommitTitle                  string             `json:"commit_title"`
	CommitAuthorName             string             `json:"commit_author_name"`
	CommitAuthorLogin            string             `json:"commit_author_login"`
	CommittedAt                  pgtype.Timestamptz `json:"committed_at"`
}

type BuildLog struct {
	BuildID   int64              `json:"build_id"`
	Sequence  int64              `json:"sequence"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DeliveryTarget struct {
	ID                int64              `json:"id"`
	PublicID          string             `json:"public_id"`
	GithubDeliveryID  int64              `json:"github_delivery_id"`
	WorkspaceID       int64              `json:"workspace_id"`
	ProjectID         int64              `json:"project_id"`
	AppID             int64              `json:"app_id"`
	AppEnvironmentID  int64              `json:"app_environment_id"`
	RequestedByUserID int64              `json:"requested_by_user_id"`
	PolicyVersion     int64              `json:"policy_version"`
	TriggerType       string             `json:"trigger_type"`
	SourceBranch      string             `json:"source_branch"`
	CommitSha         string             `json:"commit_sha"`
	BuildID           pgtype.Int8        `json:"build_id"`
	DeploymentID      pgtype.Int8        `json:"deployment_id"`
	Status            string             `json:"status"`
	ErrorCode         string             `json:"error_code"`
	ErrorMessage      string             `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type Deployment struct {
	ID                   int64              `json:"id"`
	PublicID             string             `json:"public_id"`
	WorkspaceID          int64              `json:"workspace_id"`
	AppEnvironmentID     int64              `json:"app_environment_id"`
	AppID                int64              `json:"app_id"`
	ReleaseID            int64              `json:"release_id"`
	RequestedByUserID    int64              `json:"requested_by_user_id"`
	ConfigurationVersion int64              `json:"configuration_version"`
	ConfigurationJson    []byte             `json:"configuration_json"`
	Status               string             `json:"status"`
	Message              string             `json:"message"`
	ObservedRelease      string             `json:"observed_release"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	WorkloadKind         string             `json:"workload_kind"`
	AppVolumeID          pgtype.Int8        `json:"app_volume_id"`
}

type Environment struct {
	ID         int64              `json:"id"`
	PublicID   string             `json:"public_id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	NameKey    string             `json:"name_key"`
	Version    int64              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type GithubConnectionState struct {
	ID                   int64              `json:"id"`
	StateHash            []byte             `json:"state_hash"`
	BrowserHash          []byte             `json:"browser_hash"`
	UserID               int64              `json:"user_id"`
	WorkspaceID          int64              `json:"workspace_id"`
	Step                 string             `json:"step"`
	GithubInstallationID pgtype.Int8        `json:"github_installation_id"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type GithubDelivery struct {
	ID                     int64              `json:"id"`
	DeliveryID             string             `json:"delivery_id"`
	EventType              string             `json:"event_type"`
	Action                 string             `json:"action"`
	InstallationExternalID int64              `json:"installation_external_id"`
	RepositoryID           int64              `json:"repository_id"`
	RepositoryFullName     string             `json:"repository_full_name"`
	SourceBranch           string             `json:"source_branch"`
	SourceRef              string             `json:"source_ref"`
	CommitSha              string             `json:"commit_sha"`
	TagName                string             `json:"tag_name"`
	RepositoryIds          []int64            `json:"repository_ids"`
	PayloadHash            []byte             `json:"payload_hash"`
	Status                 string             `json:"status"`
	Attempts               int32              `json:"attempts"`
	WorkerID               pgtype.Text        `json:"worker_id"`
	FencingToken           int64              `json:"fencing_token"`
	LeaseUntil             pgtype.Timestamptz `json:"lease_until"`
	ErrorCode              string             `json:"error_code"`
	ErrorMessage           string             `json:"error_message"`
	ReceivedAt             pgtype.Timestamptz `json:"received_at"`
	ProcessedAt            pgtype.Timestamptz `json:"processed_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type GithubInstallation struct {
	ID                   int64              `json:"id"`
	PublicID             string             `json:"public_id"`
	WorkspaceID          int64              `json:"workspace_id"`
	ConnectedByUserID    int64              `json:"connected_by_user_id"`
	GithubInstallationID int64              `json:"github_installation_id"`
	AccountID            int64              `json:"account_id"`
	AccountLogin         string             `json:"account_login"`
	AccountType          string             `json:"account_type"`
	RepositorySelection  string             `json:"repository_selection"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Status               string             `json:"status"`
}

type InstallationRoleAssignment struct {
	UserID    int64              `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Operation struct {
	ID                int64              `json:"id"`
	PublicID          string             `json:"public_id"`
	WorkspaceID       int64              `json:"workspace_id"`
	AppEnvironmentID  pgtype.Int8        `json:"app_environment_id"`
	DeploymentID      pgtype.Int8        `json:"deployment_id"`
	RequestedByUserID int64              `json:"requested_by_user_id"`
	Kind              string             `json:"kind"`
	Status            string             `json:"status"`
	IdempotencyHash   []byte             `json:"idempotency_hash"`
	PayloadHash       []byte             `json:"payload_hash"`
	DesiredVersion    int64              `json:"desired_version"`
	Attempts          int32              `json:"attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseUntil        pgtype.Timestamptz `json:"lease_until"`
	WorkerID          pgtype.Text        `json:"worker_id"`
	FencingToken      int64              `json:"fencing_token"`
	ErrorCode         string             `json:"error_code"`
	ErrorMessage      string             `json:"error_message"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AppVolumeID       pgtype.Int8        `json:"app_volume_id"`
}

type Parameter struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	WorkspaceID    int64              `json:"workspace_id"`
	Path           string             `json:"path"`
	Kind           string             `json:"kind"`
	Description    string             `json:"description"`
	CurrentVersion int64              `json:"current_version"`
	Version        int64              `json:"version"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ValueState     string             `json:"value_state"`
	PurgeAfter     pgtype.Timestamptz `json:"purge_after"`
	PurgedAt       pgtype.Timestamptz `json:"purged_at"`
}

type ParameterPathReservation struct {
	WorkspaceID      int64              `json:"workspace_id"`
	Path             string             `json:"path"`
	ParameterID      int64              `json:"parameter_id"`
	ParameterVersion int64              `json:"parameter_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ParameterVersion struct {
	ParameterID                  int64              `json:"parameter_id"`
	Version                      int64              `json:"version"`
	CreatedByUserID              int64              `json:"created_by_user_id"`
	PlaintextValue               pgtype.Text        `json:"plaintext_value"`
	SecretReference              pgtype.Text        `json:"secret_reference"`
	SecretBackendVersion         pgtype.Int8        `json:"secret_backend_version"`
	Fingerprint                  []byte             `json:"fingerprint"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	ValueState                   string             `json:"value_state"`
	ExpectedSecretBackendVersion pgtype.Int8        `json:"expected_secret_backend_version"`
	IdempotencyHash              []byte             `json:"idempotency_hash"`
	PayloadHash                  []byte             `json:"payload_hash"`
	RequestedPath                pgtype.Text        `json:"requested_path"`
	RequestedDescription         pgtype.Text        `json:"requested_description"`
	CompletedAt                  pgtype.Timestamptz `json:"completed_at"`
}

type PasswordCredential struct {
	UserID       int64              `json:"user_id"`
	PasswordHash string             `json:"password_hash"`
	Algorithm    string             `json:"algorithm"`
	ChangedAt    pgtype.Timestamptz `json:"changed_at"`
}

type PasswordResetGrant struct {
	ID              int64              `json:"id"`
	PublicID        string             `json:"public_id"`
	UserID          int64              `json:"user_id"`
	CodeHash        []byte             `json:"code_hash"`
	Attempts        int32              `json:"attempts"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	NameKey     string             `json:"name_key"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

type PublicationClaim struct {
	ID                          int64              `json:"id"`
	AppEnvironmentID            int64              `json:"app_environment_id"`
	EndpointName                string             `json:"endpoint_name"`
	EndpointType                string             `json:"endpoint_type"`
	Hostname                    string             `json:"hostname"`
	ExternalPort                pgtype.Int4        `json:"external_port"`
	DesiredConfigurationVersion pgtype.Int8        `json:"desired_configuration_version"`
	CurrentConfigurationVersion pgtype.Int8        `json:"current_configuration_version"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

type RecoveryCode struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	CodeHash  []byte             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Release struct {
	ID                 int64              `json:"id"`
	PublicID           string             `json:"public_id"`
	WorkspaceID        int64              `json:"workspace_id"`
	ProjectID          int64              `json:"project_id"`
	AppID              int64              `json:"app_id"`
	BuildID            int64              `json:"build_id"`
	CommitSha          string             `json:"commit_sha"`
	Image              string             `json:"image"`
	Platform           string             `json:"platform"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	AppEnvironmentID   int64              `json:"app_environment_id"`
	AvailabilityStatus string             `json:"availability_status"`
	ExpiredAt          pgtype.Timestamptz `json:"expired_at"`
}

type ReleaseGcCandidate struct {
	ReleaseID int64              `json:"release_id"`
	Image     string             `json:"image"`
	Status    string             `json:"status"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID             int64              `json:"id"`
	TokenHash      []byte             `json:"token_hash"`
	UserID         int64              `json:"user_id"`
	CsrfHash       []byte             `json:"csrf_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PublicID       string             `json:"public_id"`
	AuthVersion    int64              `json:"auth_version"`
	AssuranceLevel string             `json:"assurance_level"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	IdleExpiresAt  pgtype.Timestamptz `json:"idle_expires_at"`
}

type StorageProfile struct {
	ID                string             `json:"id"`
	DisplayName       string             `json:"display_name"`
	MinimumSizeGib    int64              `json:"minimum_size_gib"`
	MaximumSizeGib    int64              `json:"maximum_size_gib"`
	TotalCapacityGib  int64              `json:"total_capacity_gib"`
	WorkspaceQuotaGib int64              `json:"workspace_quota_gib"`
	Expandable        bool               `json:"expandable"`
	Snapshots         bool               `json:"snapshots"`
	AutomaticBackup   bool               `json:"automatic_backup"`
	Durability        string             `json:"durability"`
	RuntimeBinding    string             `json:"runtime_binding"`
	Enabled           bool               `json:"enabled"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type TotpCredential struct {
	UserID          int64              `json:"user_id"`
	SecretReference string             `json:"secret_reference"`
	SecretVersion   int64              `json:"secret_version"`
	EnabledAt       pgtype.Timestamptz `json:"enabled_at"`
	LastUsedStep    int64              `json:"last_used_step"`
}

type User struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublicID    string             `json:"public_id"`
	UsernameKey string             `json:"username_key"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	Version     int64              `json:"version"`
	AuthVersion int64              `json:"auth_version"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WebauthnCredential struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	UserID         int64              `json:"user_id"`
	CredentialID   []byte             `json:"credential_id"`
	CredentialJson []byte             `json:"credential_json"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
}

type Workspace struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	Name           string             `json:"name"`
	NamespaceName  string             `json:"namespace_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	BootstrapState string             `json:"bootstrap_state"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Version        int64              `json:"version"`
}

type WorkspaceGroup struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	NameKey     string             `json:"name_key"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceGroupMember struct {
	WorkspaceID int64              `json:"workspace_id"`
	GroupID     int64              `json:"group_id"`
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMembership struct {
	WorkspaceID int64              `json:"workspace_id"`
	UserID      int64              `json:"user_id"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
