// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddWorkspaceActor(ctx context.Context, arg AddWorkspaceActorParams) error
	ArchiveApp(ctx context.Context, arg ArchiveAppParams) (ArchiveAppRow, error)
	ArchiveEnvironment(ctx context.Context, arg ArchiveEnvironmentParams) (ArchiveEnvironmentRow, error)
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (ArchiveProjectRow, error)
	CreateApp(ctx context.Context, arg CreateAppParams) (CreateAppRow, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (CreateEnvironmentRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	FindActiveAppForUpdate(ctx context.Context, arg FindActiveAppForUpdateParams) (FindActiveAppForUpdateRow, error)
	FindActiveEnvironmentForUpdate(ctx context.Context, arg FindActiveEnvironmentForUpdateParams) (FindActiveEnvironmentForUpdateRow, error)
	FindActiveProjectForUpdate(ctx context.Context, arg FindActiveProjectForUpdateParams) (FindActiveProjectForUpdateRow, error)
	FindApp(ctx context.Context, arg FindAppParams) (FindAppRow, error)
	FindEnvironment(ctx context.Context, arg FindEnvironmentParams) (FindEnvironmentRow, error)
	FindProject(ctx context.Context, arg FindProjectParams) (FindProjectRow, error)
	FindWorkspaceForActor(ctx context.Context, arg FindWorkspaceForActorParams) (FindWorkspaceForActorRow, error)
	FindWorkspaceOperationByIdempotency(ctx context.Context, arg FindWorkspaceOperationByIdempotencyParams) (FindWorkspaceOperationByIdempotencyRow, error)
	GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error)
	GetActorByID(ctx context.Context, id int64) (GetActorByIDRow, error)
	GetActorByKey(ctx context.Context, actorKey string) (GetActorByKeyRow, error)
	GetWorkspaceByID(ctx context.Context, id int64) (GetWorkspaceByIDRow, error)
	GetWorkspaceForActor(ctx context.Context, actorID int64) (GetWorkspaceForActorRow, error)
	InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (InsertWorkspaceRow, error)
	InsertWorkspaceOperation(ctx context.Context, arg InsertWorkspaceOperationParams) (InsertWorkspaceOperationRow, error)
	ListApps(ctx context.Context, arg ListAppsParams) ([]ListAppsRow, error)
	ListEnvironments(ctx context.Context, arg ListEnvironmentsParams) ([]ListEnvironmentsRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListWorkspacesForActor(ctx context.Context, arg ListWorkspacesForActorParams) ([]ListWorkspacesForActorRow, error)
	RevokeActiveSession(ctx context.Context, arg RevokeActiveSessionParams) (int64, error)
	RevokeSession(ctx context.Context, tokenHash []byte) error
	UpdateApp(ctx context.Context, arg UpdateAppParams) (UpdateAppRow, error)
	UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (UpdateEnvironmentRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error)
	UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (UpdateWorkspaceNameRow, error)
	UpsertActor(ctx context.Context, arg UpsertActorParams) (int64, error)
	UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
