// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddWorkspaceActor(ctx context.Context, arg AddWorkspaceActorParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error)
	GetActorByID(ctx context.Context, id int64) (GetActorByIDRow, error)
	GetActorByKey(ctx context.Context, actorKey string) (GetActorByKeyRow, error)
	GetWorkspaceByID(ctx context.Context, id int64) (GetWorkspaceByIDRow, error)
	GetWorkspaceForActor(ctx context.Context, actorID int64) (GetWorkspaceForActorRow, error)
	RevokeActiveSession(ctx context.Context, arg RevokeActiveSessionParams) (int64, error)
	RevokeSession(ctx context.Context, tokenHash []byte) error
	UpsertActor(ctx context.Context, arg UpsertActorParams) (int64, error)
	UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
