apiVersion: v1
kind: ConfigMap
metadata:
  name: control-plane-config
  namespace: fruto-control-plane
data:
  FRUTO_ALLOWED_REGISTRIES: docker.io,ghcr.io
  FRUTO_OPENBAO_ADDR: ""
  FRUTO_CLICKHOUSE_URL: ""
  FRUTO_VICTORIAMETRICS_URL: ""
