apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../control-plane
images:
  - name: ghcr.io/fruto-platform/control-plane-api
    newName: fruto-control-plane-api
    newTag: local
  - name: ghcr.io/fruto-platform/console-web
    newName: fruto-console-web
    newTag: local
patches:
  - path: control-plane-api-image-pull-policy.yaml
  - path: console-web-image-pull-policy.yaml
  - path: migrate-image-pull-policy.yaml
  - path: configmap.yaml
  - path: optional-external-secrets.yaml
  - path: delete-delivery-worker.yaml
  - path: delete-bootstrap-job.yaml
