apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../control-plane
images:
  - name: ghcr.io/fruto-platform/control-plane-api
    newName: fruto-control-plane-api
    newTag: local
  - name: ghcr.io/fruto-platform/console-web
    newName: fruto-console-web
    newTag: local
patches:
  - path: image-pull-policy.yaml
