apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: molejo-observability
spec:
  template:
    spec:
      nodeSelector:
        fruto.cleidsonoliveira.dev/role: data
      tolerations:
        - key: fruto.cleidsonoliveira.dev/workload
          operator: Equal
          value: data
          effect: NoSchedule
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoria-metrics
  namespace: molejo-observability
spec:
  template:
    spec:
      nodeSelector:
        fruto.cleidsonoliveira.dev/role: data
      tolerations:
        - key: fruto.cleidsonoliveira.dev/workload
          operator: Equal
          value: data
          effect: NoSchedule
