apiVersion: platform.molejo.dev/v1alpha1
kind: ClusterTLSProfile
metadata:
  name: default
spec:
  management: Managed
  domains:
    - "*.apps.molejo.dev"
  certificate:
    driver: cert-manager
    targetSecretRef:
      namespace: molejo-system
      name: apps-molejo-dev-tls
    config:
      issuer:
        type: acme
        environment: staging
        email: replace@example.com
      challenge:
        type: dns01
        solver: cloudflare
        credentialSecretRef:
          namespace: cert-manager
          name: cloudflare-dns-token
