apiVersion: platform.molejo.dev/v1alpha1
kind: ClusterTLSProfile
metadata:
  name: default
spec:
  management: External
  domains:
    - "*.apps.molejo.dev"
  certificate:
    driver: existing-secret
    targetSecretRef:
      namespace: molejo-system
      name: apps-molejo-dev-tls
