apiVersion: config.molejo.dev/v1alpha1
kind: TLSSetup
metadata:
  name: molejo-dev
spec:
  dnsNames:
    - molejo.dev
    - "*.molejo.dev"
    - "*.stateful.molejo.dev"
  targetSecretRef:
    namespace: molejo-system
    name: molejo-dev-tls
