apiVersion: v1
kind: Secret
metadata:
  name: molejo-agent-identity
  namespace: fruto-system
  labels:
    app.kubernetes.io/name: cluster-agent
    app.kubernetes.io/part-of: fruto-platform
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: molejo-agent-enrollment
  namespace: fruto-system
  labels:
    app.kubernetes.io/name: cluster-agent
    app.kubernetes.io/part-of: fruto-platform
type: Opaque
