apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - postgres.yaml
  - services.yaml
  - bootstrap-job.yaml
  - deployments.yaml
configMapGenerator:
  - name: control-plane-config
    namespace: molejo-control-plane
    envs:
      - config.env
    options:
      labels:
        app.kubernetes.io/name: control-plane-api
        app.kubernetes.io/part-of: molejo-platform
