apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - service-account.yaml
  - services.yaml
  - deployments.yaml
  - migration-job.yaml
  - http-route.yaml
