apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - services.yaml
  - deployments.yaml
  - migration-job.yaml
  - bootstrap-job.yaml
  - http-route.yaml
configMapGenerator:
  - name: control-plane-config
    namespace: fruto-control-plane
    envs:
      - config.env
    options:
      immutable: true
      labels:
        app.kubernetes.io/managed-by: molejo-release
        molejo.dev/configuration-family: control-plane-config
