apiVersion: v1
kind: Namespace
metadata:
  name: fruto-control-plane
  labels:
    app.kubernetes.io/part-of: fruto-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: fruto-workspaces
  annotations:
    platform.fruto.calouro.tech/control-plane-owner: fruto-control-plane
  labels:
    app.kubernetes.io/part-of: fruto-platform
    app.kubernetes.io/managed-by: fruto-control-plane
