apiVersion: v1
kind: Service
metadata:
  name: control-plane-api
  namespace: fruto-control-plane
spec:
  selector:
    app.kubernetes.io/name: control-plane-api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: console-web
  namespace: fruto-control-plane
spec:
  selector:
    app.kubernetes.io/name: console-web
  ports:
    - name: http
      port: 8080
      targetPort: http
