apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane-api
  namespace: molejo-control-plane
  labels:
    app.kubernetes.io/name: control-plane-api
    app.kubernetes.io/part-of: molejo-platform
automountServiceAccountToken: false
