import type { components } from "./generated/control-plane";

export type ActorRole = components["schemas"]["Session"]["actor"]["role"];
export type Session = components["schemas"]["Session"];
export type Workspace = components["schemas"]["Workspace"];
export type HierarchyInput = components["schemas"]["HierarchyInput"];
export type Project = components["schemas"]["Project"];
export type Environment = components["schemas"]["Environment"];
export type App = components["schemas"]["App"];
export type GitHubInstallation = components["schemas"]["GitHubInstallation"];
export type GitHubRepository = components["schemas"]["GitHubRepository"];
export type GitHubSource = components["schemas"]["GitHubSource"];
export type GitHubSourceInput = components["schemas"]["GitHubSourceInput"];
export type BuildInput = components["schemas"]["BuildInput"];
export type Build = components["schemas"]["Build"];
export type BuildLog = components["schemas"]["BuildLog"];
export type Release = components["schemas"]["Release"];
export type ReleaseDeploymentIntent = components["schemas"]["ReleaseDeploymentIntent"];
export type Deployment = components["schemas"]["Deployment"];
export type Operation = components["schemas"]["Operation"];
export type ApiError = components["schemas"]["Error"];
export type WorkspaceMutationAccepted = { workspace: Workspace; operation: Operation };
export type DeploymentMutationAccepted = { deployment: Deployment; operation: Operation };
