apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-operator
  namespace: molejo-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-boundary-controller
  namespace: molejo-system
