// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: molejo/clusteragent/v1alpha1/agent.proto

package clusteragentv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectRequest_Hello
	//	*ConnectRequest_Heartbeat
	//	*ConnectRequest_RuntimeResult
	Payload       isConnectRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetPayload() isConnectRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectRequest) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ConnectRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ConnectRequest) GetRuntimeResult() *RuntimeResult {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_RuntimeResult); ok {
			return x.RuntimeResult
		}
	}
	return nil
}

type isConnectRequest_Payload interface {
	isConnectRequest_Payload()
}

type ConnectRequest_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ConnectRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ConnectRequest_RuntimeResult struct {
	RuntimeResult *RuntimeResult `protobuf:"bytes,3,opt,name=runtime_result,json=runtimeResult,proto3,oneof"`
}

func (*ConnectRequest_Hello) isConnectRequest_Payload() {}

func (*ConnectRequest_Heartbeat) isConnectRequest_Payload() {}

func (*ConnectRequest_RuntimeResult) isConnectRequest_Payload() {}

type ConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectResponse_Hello
	//	*ConnectResponse_HeartbeatAck
	//	*ConnectResponse_RuntimeCommand
	Payload       isConnectResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetPayload() isConnectResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectResponse) GetHello() *ControlPlaneHello {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ConnectResponse) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ConnectResponse) GetRuntimeCommand() *RuntimeCommand {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_RuntimeCommand); ok {
			return x.RuntimeCommand
		}
	}
	return nil
}

type isConnectResponse_Payload interface {
	isConnectResponse_Payload()
}

type ConnectResponse_Hello struct {
	Hello *ControlPlaneHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ConnectResponse_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ConnectResponse_RuntimeCommand struct {
	RuntimeCommand *RuntimeCommand `protobuf:"bytes,3,opt,name=runtime_command,json=runtimeCommand,proto3,oneof"`
}

func (*ConnectResponse_Hello) isConnectResponse_Payload() {}

func (*ConnectResponse_HeartbeatAck) isConnectResponse_Payload() {}

func (*ConnectResponse_RuntimeCommand) isConnectResponse_Payload() {}

type AgentHello struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	InstallationId            string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	AgentVersion              string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ClusterUid                string                 `protobuf:"bytes,3,opt,name=cluster_uid,json=clusterUid,proto3" json:"cluster_uid,omitempty"`
	KubernetesVersion         string                 `protobuf:"bytes,4,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	Capabilities              []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SupportedProtocolVersions []string               `protobuf:"bytes,6,rep,name=supported_protocol_versions,json=supportedProtocolVersions,proto3" json:"supported_protocol_versions,omitempty"`
	TrustBundleId             string                 `protobuf:"bytes,7,opt,name=trust_bundle_id,json=trustBundleId,proto3" json:"trust_bundle_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHello) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetClusterUid() string {
	if x != nil {
		return x.ClusterUid
	}
	return ""
}

func (x *AgentHello) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *AgentHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentHello) GetSupportedProtocolVersions() []string {
	if x != nil {
		return x.SupportedProtocolVersions
	}
	return nil
}

func (x *AgentHello) GetTrustBundleId() string {
	if x != nil {
		return x.TrustBundleId
	}
	return ""
}

type ControlPlaneHello struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion          string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	ServerTimeUnix           int64                  `protobuf:"varint,3,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	Capabilities             []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SessionId                string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TrustBundleId            string                 `protobuf:"bytes,6,opt,name=trust_bundle_id,json=trustBundleId,proto3" json:"trust_bundle_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ControlPlaneHello) Reset() {
	*x = ControlPlaneHello{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneHello) ProtoMessage() {}

func (x *ControlPlaneHello) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneHello.ProtoReflect.Descriptor instead.
func (*ControlPlaneHello) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ControlPlaneHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ControlPlaneHello) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *ControlPlaneHello) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

func (x *ControlPlaneHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ControlPlaneHello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlPlaneHello) GetTrustBundleId() string {
	if x != nil {
		return x.TrustBundleId
	}
	return ""
}

type Heartbeat struct {
	state                       protoimpl.MessageState   `protogen:"open.v1"`
	Sequence                    uint64                   `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentAtUnix                  int64                    `protobuf:"varint,2,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	Observations                []*RuntimeObservation    `protobuf:"bytes,3,rep,name=observations,proto3" json:"observations,omitempty"`
	ObservationSnapshotComplete bool                     `protobuf:"varint,4,opt,name=observation_snapshot_complete,json=observationSnapshotComplete,proto3" json:"observation_snapshot_complete,omitempty"`
	SessionId                   string                   `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CapabilityObservations      []*CapabilityObservation `protobuf:"bytes,6,rep,name=capability_observations,json=capabilityObservations,proto3" json:"capability_observations,omitempty"`
	CapabilitySnapshotComplete  bool                     `protobuf:"varint,7,opt,name=capability_snapshot_complete,json=capabilitySnapshotComplete,proto3" json:"capability_snapshot_complete,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

func (x *Heartbeat) GetObservations() []*RuntimeObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *Heartbeat) GetObservationSnapshotComplete() bool {
	if x != nil {
		return x.ObservationSnapshotComplete
	}
	return false
}

func (x *Heartbeat) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Heartbeat) GetCapabilityObservations() []*CapabilityObservation {
	if x != nil {
		return x.CapabilityObservations
	}
	return nil
}

func (x *Heartbeat) GetCapabilitySnapshotComplete() bool {
	if x != nil {
		return x.CapabilitySnapshotComplete
	}
	return false
}

type CapabilityObservation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId     string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	ContractVersion  string                 `protobuf:"bytes,2,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	Support          string                 `protobuf:"bytes,3,opt,name=support,proto3" json:"support,omitempty"`
	Health           string                 `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	ProviderKind     string                 `protobuf:"bytes,5,opt,name=provider_kind,json=providerKind,proto3" json:"provider_kind,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,6,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	SanitizedMessage string                 `protobuf:"bytes,7,opt,name=sanitized_message,json=sanitizedMessage,proto3" json:"sanitized_message,omitempty"`
	Limitations      []string               `protobuf:"bytes,8,rep,name=limitations,proto3" json:"limitations,omitempty"`
	SampledAtUnix    int64                  `protobuf:"varint,9,opt,name=sampled_at_unix,json=sampledAtUnix,proto3" json:"sampled_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilityObservation) Reset() {
	*x = CapabilityObservation{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityObservation) ProtoMessage() {}

func (x *CapabilityObservation) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityObservation.ProtoReflect.Descriptor instead.
func (*CapabilityObservation) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilityObservation) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *CapabilityObservation) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *CapabilityObservation) GetSupport() string {
	if x != nil {
		return x.Support
	}
	return ""
}

func (x *CapabilityObservation) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *CapabilityObservation) GetProviderKind() string {
	if x != nil {
		return x.ProviderKind
	}
	return ""
}

func (x *CapabilityObservation) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CapabilityObservation) GetSanitizedMessage() string {
	if x != nil {
		return x.SanitizedMessage
	}
	return ""
}

func (x *CapabilityObservation) GetLimitations() []string {
	if x != nil {
		return x.Limitations
	}
	return nil
}

func (x *CapabilityObservation) GetSampledAtUnix() int64 {
	if x != nil {
		return x.SampledAtUnix
	}
	return 0
}

type RuntimeObservation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Kind               string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace          string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State              string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Message            string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Generation         int64                  `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"`
	ObservedGeneration int64                  `protobuf:"varint,7,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	ObservedRelease    string                 `protobuf:"bytes,8,opt,name=observed_release,json=observedRelease,proto3" json:"observed_release,omitempty"`
	ObservedSizeGib    int64                  `protobuf:"varint,9,opt,name=observed_size_gib,json=observedSizeGib,proto3" json:"observed_size_gib,omitempty"`
	DesiredVersion     int64                  `protobuf:"varint,10,opt,name=desired_version,json=desiredVersion,proto3" json:"desired_version,omitempty"`
	SpecHash           string                 `protobuf:"bytes,11,opt,name=spec_hash,json=specHash,proto3" json:"spec_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RuntimeObservation) Reset() {
	*x = RuntimeObservation{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeObservation) ProtoMessage() {}

func (x *RuntimeObservation) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeObservation.ProtoReflect.Descriptor instead.
func (*RuntimeObservation) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RuntimeObservation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RuntimeObservation) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RuntimeObservation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeObservation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RuntimeObservation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeObservation) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RuntimeObservation) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *RuntimeObservation) GetObservedRelease() string {
	if x != nil {
		return x.ObservedRelease
	}
	return ""
}

func (x *RuntimeObservation) GetObservedSizeGib() int64 {
	if x != nil {
		return x.ObservedSizeGib
	}
	return 0
}

func (x *RuntimeObservation) GetDesiredVersion() int64 {
	if x != nil {
		return x.DesiredVersion
	}
	return 0
}

func (x *RuntimeObservation) GetSpecHash() string {
	if x != nil {
		return x.SpecHash
	}
	return ""
}

type HeartbeatAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sequence       uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ReceivedAtUnix int64                  `protobuf:"varint,2,opt,name=received_at_unix,json=receivedAtUnix,proto3" json:"received_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HeartbeatAck) GetReceivedAtUnix() int64 {
	if x != nil {
		return x.ReceivedAtUnix
	}
	return 0
}

type RuntimeCommand struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CommandId            string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OperationId          string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	DesiredVersion       int64                  `protobuf:"varint,3,opt,name=desired_version,json=desiredVersion,proto3" json:"desired_version,omitempty"`
	FencingToken         int64                  `protobuf:"varint,4,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	DeadlineUnix         int64                  `protobuf:"varint,5,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	Kind                 string                 `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	PayloadJson          []byte                 `protobuf:"bytes,7,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	PayloadSchemaVersion string                 `protobuf:"bytes,8,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RuntimeCommand) Reset() {
	*x = RuntimeCommand{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCommand) ProtoMessage() {}

func (x *RuntimeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCommand.ProtoReflect.Descriptor instead.
func (*RuntimeCommand) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RuntimeCommand) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RuntimeCommand) GetDesiredVersion() int64 {
	if x != nil {
		return x.DesiredVersion
	}
	return 0
}

func (x *RuntimeCommand) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *RuntimeCommand) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *RuntimeCommand) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RuntimeCommand) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *RuntimeCommand) GetPayloadSchemaVersion() string {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return ""
}

type RuntimeResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	FencingToken    int64                  `protobuf:"varint,2,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ObservedRelease string                 `protobuf:"bytes,5,opt,name=observed_release,json=observedRelease,proto3" json:"observed_release,omitempty"`
	VolumeState     string                 `protobuf:"bytes,6,opt,name=volume_state,json=volumeState,proto3" json:"volume_state,omitempty"`
	VolumeMessage   string                 `protobuf:"bytes,7,opt,name=volume_message,json=volumeMessage,proto3" json:"volume_message,omitempty"`
	ObservedSizeGib int64                  `protobuf:"varint,8,opt,name=observed_size_gib,json=observedSizeGib,proto3" json:"observed_size_gib,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,9,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Retryable       bool                   `protobuf:"varint,10,opt,name=retryable,proto3" json:"retryable,omitempty"`
	DesiredVersion  int64                  `protobuf:"varint,11,opt,name=desired_version,json=desiredVersion,proto3" json:"desired_version,omitempty"`
	SpecHash        string                 `protobuf:"bytes,12,opt,name=spec_hash,json=specHash,proto3" json:"spec_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeResult) Reset() {
	*x = RuntimeResult{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeResult) ProtoMessage() {}

func (x *RuntimeResult) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeResult.ProtoReflect.Descriptor instead.
func (*RuntimeResult) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RuntimeResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RuntimeResult) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *RuntimeResult) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RuntimeResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeResult) GetObservedRelease() string {
	if x != nil {
		return x.ObservedRelease
	}
	return ""
}

func (x *RuntimeResult) GetVolumeState() string {
	if x != nil {
		return x.VolumeState
	}
	return ""
}

func (x *RuntimeResult) GetVolumeMessage() string {
	if x != nil {
		return x.VolumeMessage
	}
	return ""
}

func (x *RuntimeResult) GetObservedSizeGib() int64 {
	if x != nil {
		return x.ObservedSizeGib
	}
	return 0
}

func (x *RuntimeResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RuntimeResult) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *RuntimeResult) GetDesiredVersion() int64 {
	if x != nil {
		return x.DesiredVersion
	}
	return 0
}

func (x *RuntimeResult) GetSpecHash() string {
	if x != nil {
		return x.SpecHash
	}
	return ""
}

type RenewCertificateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	CsrPem         []byte                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RenewCertificateRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *RenewCertificateRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *RenewCertificateRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type RenewCertificateResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	InstallationId         string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	CertificatePem         []byte                 `protobuf:"bytes,2,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	CaCertificatePem       []byte                 `protobuf:"bytes,3,opt,name=ca_certificate_pem,json=caCertificatePem,proto3" json:"ca_certificate_pem,omitempty"`
	ExpiresAtUnix          int64                  `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	ServerCaCertificatePem []byte                 `protobuf:"bytes,5,opt,name=server_ca_certificate_pem,json=serverCaCertificatePem,proto3" json:"server_ca_certificate_pem,omitempty"`
	TrustBundleId          string                 `protobuf:"bytes,6,opt,name=trust_bundle_id,json=trustBundleId,proto3" json:"trust_bundle_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RenewCertificateResponse) Reset() {
	*x = RenewCertificateResponse{}
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateResponse) ProtoMessage() {}

func (x *RenewCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateResponse.ProtoReflect.Descriptor instead.
func (*RenewCertificateResponse) Descriptor() ([]byte, []int) {
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RenewCertificateResponse) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *RenewCertificateResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *RenewCertificateResponse) GetCaCertificatePem() []byte {
	if x != nil {
		return x.CaCertificatePem
	}
	return nil
}

func (x *RenewCertificateResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *RenewCertificateResponse) GetServerCaCertificatePem() []byte {
	if x != nil {
		return x.ServerCaCertificatePem
	}
	return nil
}

func (x *RenewCertificateResponse) GetTrustBundleId() string {
	if x != nil {
		return x.TrustBundleId
	}
	return ""
}

var File_molejo_clusteragent_v1alpha1_agent_proto protoreflect.FileDescriptor

const file_molejo_clusteragent_v1alpha1_agent_proto_rawDesc = "" +
	"\n" +
	"(molejo/clusteragent/v1alpha1/agent.proto\x12\x1cmolejo.clusteragent.v1alpha1\"\xfc\x01\n" +
	"\x0eConnectRequest\x12@\n" +
	"\x05hello\x18\x01 \x01(\v2(.molejo.clusteragent.v1alpha1.AgentHelloH\x00R\x05hello\x12G\n" +
	"\theartbeat\x18\x02 \x01(\v2'.molejo.clusteragent.v1alpha1.HeartbeatH\x00R\theartbeat\x12T\n" +
	"\x0eruntime_result\x18\x03 \x01(\v2+.molejo.clusteragent.v1alpha1.RuntimeResultH\x00R\rruntimeResultB\t\n" +
	"\apayload\"\x91\x02\n" +
	"\x0fConnectResponse\x12G\n" +
	"\x05hello\x18\x01 \x01(\v2/.molejo.clusteragent.v1alpha1.ControlPlaneHelloH\x00R\x05hello\x12Q\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2*.molejo.clusteragent.v1alpha1.HeartbeatAckH\x00R\fheartbeatAck\x12W\n" +
	"\x0fruntime_command\x18\x03 \x01(\v2,.molejo.clusteragent.v1alpha1.RuntimeCommandH\x00R\x0eruntimeCommandB\t\n" +
	"\apayload\"\xb6\x02\n" +
	"\n" +
	"AgentHello\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vcluster_uid\x18\x03 \x01(\tR\n" +
	"clusterUid\x12-\n" +
	"\x12kubernetes_version\x18\x04 \x01(\tR\x11kubernetesVersion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12>\n" +
	"\x1bsupported_protocol_versions\x18\x06 \x03(\tR\x19supportedProtocolVersions\x12&\n" +
	"\x0ftrust_bundle_id\x18\a \x01(\tR\rtrustBundleId\"\x91\x02\n" +
	"\x11ControlPlaneHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\x05R\x18heartbeatIntervalSeconds\x12(\n" +
	"\x10server_time_unix\x18\x03 \x01(\x03R\x0eserverTimeUnix\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12&\n" +
	"\x0ftrust_bundle_id\x18\x06 \x01(\tR\rtrustBundleId\"\xb2\x03\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12 \n" +
	"\fsent_at_unix\x18\x02 \x01(\x03R\n" +
	"sentAtUnix\x12T\n" +
	"\fobservations\x18\x03 \x03(\v20.molejo.clusteragent.v1alpha1.RuntimeObservationR\fobservations\x12B\n" +
	"\x1dobservation_snapshot_complete\x18\x04 \x01(\bR\x1bobservationSnapshotComplete\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12l\n" +
	"\x17capability_observations\x18\x06 \x03(\v23.molejo.clusteragent.v1alpha1.CapabilityObservationR\x16capabilityObservations\x12@\n" +
	"\x1ccapability_snapshot_complete\x18\a \x01(\bR\x1acapabilitySnapshotComplete\"\xd6\x02\n" +
	"\x15CapabilityObservation\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12)\n" +
	"\x10contract_version\x18\x02 \x01(\tR\x0fcontractVersion\x12\x18\n" +
	"\asupport\x18\x03 \x01(\tR\asupport\x12\x16\n" +
	"\x06health\x18\x04 \x01(\tR\x06health\x12#\n" +
	"\rprovider_kind\x18\x05 \x01(\tR\fproviderKind\x12\x1f\n" +
	"\vreason_code\x18\x06 \x01(\tR\n" +
	"reasonCode\x12+\n" +
	"\x11sanitized_message\x18\a \x01(\tR\x10sanitizedMessage\x12 \n" +
	"\vlimitations\x18\b \x03(\tR\vlimitations\x12&\n" +
	"\x0fsampled_at_unix\x18\t \x01(\x03R\rsampledAtUnix\"\xf8\x02\n" +
	"\x12RuntimeObservation\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"generation\x18\x06 \x01(\x03R\n" +
	"generation\x12/\n" +
	"\x13observed_generation\x18\a \x01(\x03R\x12observedGeneration\x12)\n" +
	"\x10observed_release\x18\b \x01(\tR\x0fobservedRelease\x12*\n" +
	"\x11observed_size_gib\x18\t \x01(\x03R\x0fobservedSizeGib\x12'\n" +
	"\x0fdesired_version\x18\n" +
	" \x01(\x03R\x0edesiredVersion\x12\x1b\n" +
	"\tspec_hash\x18\v \x01(\tR\bspecHash\"T\n" +
	"\fHeartbeatAck\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12(\n" +
	"\x10received_at_unix\x18\x02 \x01(\x03R\x0ereceivedAtUnix\"\xb2\x02\n" +
	"\x0eRuntimeCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12'\n" +
	"\x0fdesired_version\x18\x03 \x01(\x03R\x0edesiredVersion\x12#\n" +
	"\rfencing_token\x18\x04 \x01(\x03R\ffencingToken\x12#\n" +
	"\rdeadline_unix\x18\x05 \x01(\x03R\fdeadlineUnix\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\tR\x04kind\x12!\n" +
	"\fpayload_json\x18\a \x01(\fR\vpayloadJson\x124\n" +
	"\x16payload_schema_version\x18\b \x01(\tR\x14payloadSchemaVersion\"\xa7\x03\n" +
	"\rRuntimeResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12#\n" +
	"\rfencing_token\x18\x02 \x01(\x03R\ffencingToken\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12)\n" +
	"\x10observed_release\x18\x05 \x01(\tR\x0fobservedRelease\x12!\n" +
	"\fvolume_state\x18\x06 \x01(\tR\vvolumeState\x12%\n" +
	"\x0evolume_message\x18\a \x01(\tR\rvolumeMessage\x12*\n" +
	"\x11observed_size_gib\x18\b \x01(\x03R\x0fobservedSizeGib\x12\x1d\n" +
	"\n" +
	"error_code\x18\t \x01(\tR\terrorCode\x12\x1c\n" +
	"\tretryable\x18\n" +
	" \x01(\bR\tretryable\x12'\n" +
	"\x0fdesired_version\x18\v \x01(\x03R\x0edesiredVersion\x12\x1b\n" +
	"\tspec_hash\x18\f \x01(\tR\bspecHash\"z\n" +
	"\x17RenewCertificateRequest\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\fR\x06csrPem\"\xa5\x02\n" +
	"\x18RenewCertificateResponse\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12'\n" +
	"\x0fcertificate_pem\x18\x02 \x01(\fR\x0ecertificatePem\x12,\n" +
	"\x12ca_certificate_pem\x18\x03 \x01(\fR\x10caCertificatePem\x12&\n" +
	"\x0fexpires_at_unix\x18\x04 \x01(\x03R\rexpiresAtUnix\x129\n" +
	"\x19server_ca_certificate_pem\x18\x05 \x01(\fR\x16serverCaCertificatePem\x12&\n" +
	"\x0ftrust_bundle_id\x18\x06 \x01(\tR\rtrustBundleId2\x85\x02\n" +
	"\x13ClusterAgentService\x12j\n" +
	"\aConnect\x12,.molejo.clusteragent.v1alpha1.ConnectRequest\x1a-.molejo.clusteragent.v1alpha1.ConnectResponse(\x010\x01\x12\x81\x01\n" +
	"\x10RenewCertificate\x125.molejo.clusteragent.v1alpha1.RenewCertificateRequest\x1a6.molejo.clusteragent.v1alpha1.RenewCertificateResponseB_Z]github.com/molejo-platform/molejo/contracts/molejo/clusteragent/v1alpha1;clusteragentv1alpha1b\x06proto3"

var (
	file_molejo_clusteragent_v1alpha1_agent_proto_rawDescOnce sync.Once
	file_molejo_clusteragent_v1alpha1_agent_proto_rawDescData []byte
)

func file_molejo_clusteragent_v1alpha1_agent_proto_rawDescGZIP() []byte {
	file_molejo_clusteragent_v1alpha1_agent_proto_rawDescOnce.Do(func() {
		file_molejo_clusteragent_v1alpha1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_molejo_clusteragent_v1alpha1_agent_proto_rawDesc), len(file_molejo_clusteragent_v1alpha1_agent_proto_rawDesc)))
	})
	return file_molejo_clusteragent_v1alpha1_agent_proto_rawDescData
}

var file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_molejo_clusteragent_v1alpha1_agent_proto_goTypes = []any{
	(*ConnectRequest)(nil),           // 0: molejo.clusteragent.v1alpha1.ConnectRequest
	(*ConnectResponse)(nil),          // 1: molejo.clusteragent.v1alpha1.ConnectResponse
	(*AgentHello)(nil),               // 2: molejo.clusteragent.v1alpha1.AgentHello
	(*ControlPlaneHello)(nil),        // 3: molejo.clusteragent.v1alpha1.ControlPlaneHello
	(*Heartbeat)(nil),                // 4: molejo.clusteragent.v1alpha1.Heartbeat
	(*CapabilityObservation)(nil),    // 5: molejo.clusteragent.v1alpha1.CapabilityObservation
	(*RuntimeObservation)(nil),       // 6: molejo.clusteragent.v1alpha1.RuntimeObservation
	(*HeartbeatAck)(nil),             // 7: molejo.clusteragent.v1alpha1.HeartbeatAck
	(*RuntimeCommand)(nil),           // 8: molejo.clusteragent.v1alpha1.RuntimeCommand
	(*RuntimeResult)(nil),            // 9: molejo.clusteragent.v1alpha1.RuntimeResult
	(*RenewCertificateRequest)(nil),  // 10: molejo.clusteragent.v1alpha1.RenewCertificateRequest
	(*RenewCertificateResponse)(nil), // 11: molejo.clusteragent.v1alpha1.RenewCertificateResponse
}
var file_molejo_clusteragent_v1alpha1_agent_proto_depIdxs = []int32{
	2,  // 0: molejo.clusteragent.v1alpha1.ConnectRequest.hello:type_name -> molejo.clusteragent.v1alpha1.AgentHello
	4,  // 1: molejo.clusteragent.v1alpha1.ConnectRequest.heartbeat:type_name -> molejo.clusteragent.v1alpha1.Heartbeat
	9,  // 2: molejo.clusteragent.v1alpha1.ConnectRequest.runtime_result:type_name -> molejo.clusteragent.v1alpha1.RuntimeResult
	3,  // 3: molejo.clusteragent.v1alpha1.ConnectResponse.hello:type_name -> molejo.clusteragent.v1alpha1.ControlPlaneHello
	7,  // 4: molejo.clusteragent.v1alpha1.ConnectResponse.heartbeat_ack:type_name -> molejo.clusteragent.v1alpha1.HeartbeatAck
	8,  // 5: molejo.clusteragent.v1alpha1.ConnectResponse.runtime_command:type_name -> molejo.clusteragent.v1alpha1.RuntimeCommand
	6,  // 6: molejo.clusteragent.v1alpha1.Heartbeat.observations:type_name -> molejo.clusteragent.v1alpha1.RuntimeObservation
	5,  // 7: molejo.clusteragent.v1alpha1.Heartbeat.capability_observations:type_name -> molejo.clusteragent.v1alpha1.CapabilityObservation
	0,  // 8: molejo.clusteragent.v1alpha1.ClusterAgentService.Connect:input_type -> molejo.clusteragent.v1alpha1.ConnectRequest
	10, // 9: molejo.clusteragent.v1alpha1.ClusterAgentService.RenewCertificate:input_type -> molejo.clusteragent.v1alpha1.RenewCertificateRequest
	1,  // 10: molejo.clusteragent.v1alpha1.ClusterAgentService.Connect:output_type -> molejo.clusteragent.v1alpha1.ConnectResponse
	11, // 11: molejo.clusteragent.v1alpha1.ClusterAgentService.RenewCertificate:output_type -> molejo.clusteragent.v1alpha1.RenewCertificateResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_molejo_clusteragent_v1alpha1_agent_proto_init() }
func file_molejo_clusteragent_v1alpha1_agent_proto_init() {
	if File_molejo_clusteragent_v1alpha1_agent_proto != nil {
		return
	}
	file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnectRequest_Hello)(nil),
		(*ConnectRequest_Heartbeat)(nil),
		(*ConnectRequest_RuntimeResult)(nil),
	}
	file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ConnectResponse_Hello)(nil),
		(*ConnectResponse_HeartbeatAck)(nil),
		(*ConnectResponse_RuntimeCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_molejo_clusteragent_v1alpha1_agent_proto_rawDesc), len(file_molejo_clusteragent_v1alpha1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_molejo_clusteragent_v1alpha1_agent_proto_goTypes,
		DependencyIndexes: file_molejo_clusteragent_v1alpha1_agent_proto_depIdxs,
		MessageInfos:      file_molejo_clusteragent_v1alpha1_agent_proto_msgTypes,
	}.Build()
	File_molejo_clusteragent_v1alpha1_agent_proto = out.File
	file_molejo_clusteragent_v1alpha1_agent_proto_goTypes = nil
	file_molejo_clusteragent_v1alpha1_agent_proto_depIdxs = nil
}
