// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: molejo/clusteragent/v1alpha1/agent.proto

package clusteragentv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterAgentService_Connect_FullMethodName                 = "/molejo.clusteragent.v1alpha1.ClusterAgentService/Connect"
	ClusterAgentService_OpenRuntimeQueryChannel_FullMethodName = "/molejo.clusteragent.v1alpha1.ClusterAgentService/OpenRuntimeQueryChannel"
	ClusterAgentService_RenewCertificate_FullMethodName        = "/molejo.clusteragent.v1alpha1.ClusterAgentService/RenewCertificate"
)

// ClusterAgentServiceClient is the client API for ClusterAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterAgentServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error)
	OpenRuntimeQueryChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenRuntimeQueryChannelRequest, OpenRuntimeQueryChannelResponse], error)
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error)
}

type clusterAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterAgentServiceClient(cc grpc.ClientConnInterface) ClusterAgentServiceClient {
	return &clusterAgentServiceClient{cc}
}

func (c *clusterAgentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterAgentService_ServiceDesc.Streams[0], ClusterAgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectRequest, ConnectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterAgentService_ConnectClient = grpc.BidiStreamingClient[ConnectRequest, ConnectResponse]

func (c *clusterAgentServiceClient) OpenRuntimeQueryChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenRuntimeQueryChannelRequest, OpenRuntimeQueryChannelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterAgentService_ServiceDesc.Streams[1], ClusterAgentService_OpenRuntimeQueryChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenRuntimeQueryChannelRequest, OpenRuntimeQueryChannelResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterAgentService_OpenRuntimeQueryChannelClient = grpc.BidiStreamingClient[OpenRuntimeQueryChannelRequest, OpenRuntimeQueryChannelResponse]

func (c *clusterAgentServiceClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertificateResponse)
	err := c.cc.Invoke(ctx, ClusterAgentService_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterAgentServiceServer is the server API for ClusterAgentService service.
// All implementations must embed UnimplementedClusterAgentServiceServer
// for forward compatibility.
type ClusterAgentServiceServer interface {
	Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error
	OpenRuntimeQueryChannel(grpc.BidiStreamingServer[OpenRuntimeQueryChannelRequest, OpenRuntimeQueryChannelResponse]) error
	RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error)
	mustEmbedUnimplementedClusterAgentServiceServer()
}

// UnimplementedClusterAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterAgentServiceServer struct{}

func (UnimplementedClusterAgentServiceServer) Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedClusterAgentServiceServer) OpenRuntimeQueryChannel(grpc.BidiStreamingServer[OpenRuntimeQueryChannelRequest, OpenRuntimeQueryChannelResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenRuntimeQueryChannel not implemented")
}
func (UnimplementedClusterAgentServiceServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedClusterAgentServiceServer) mustEmbedUnimplementedClusterAgentServiceServer() {}
func (UnimplementedClusterAgentServiceServer) testEmbeddedByValue()                             {}

// UnsafeClusterAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterAgentServiceServer will
// result in compilation errors.
type UnsafeClusterAgentServiceServer interface {
	mustEmbedUnimplementedClusterAgentServiceServer()
}

func RegisterClusterAgentServiceServer(s grpc.ServiceRegistrar, srv ClusterAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterAgentService_ServiceDesc, srv)
}

func _ClusterAgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterAgentServiceServer).Connect(&grpc.GenericServerStream[ConnectRequest, ConnectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterAgentService_ConnectServer = grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]

func _ClusterAgentService_OpenRuntimeQueryChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterAgentServiceServer).OpenRuntimeQueryChannel(&grpc.GenericServerStream[OpenRuntimeQueryChannelRequest, OpenRuntimeQueryChannelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterAgentService_OpenRuntimeQueryChannelServer = grpc.BidiStreamingServer[OpenRuntimeQueryChannelRequest, OpenRuntimeQueryChannelResponse]

func _ClusterAgentService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterAgentServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterAgentService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterAgentServiceServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterAgentService_ServiceDesc is the grpc.ServiceDesc for ClusterAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "molejo.clusteragent.v1alpha1.ClusterAgentService",
	HandlerType: (*ClusterAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenewCertificate",
			Handler:    _ClusterAgentService_RenewCertificate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ClusterAgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenRuntimeQueryChannel",
			Handler:       _ClusterAgentService_OpenRuntimeQueryChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "molejo/clusteragent/v1alpha1/agent.proto",
}
