apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../crds
  - ../operator
  - ../cluster-agent
  - ../control-plane-lab
patches:
  - path: stateful-scheduling-lab.yaml
  - path: cluster-agent-private-registry.yaml
