apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-accounts-rbac.yaml
  - configmaps.yaml
  - services.yaml
  - workloads.yaml
  - network-policies.yaml
