apiVersion: v1
kind: Namespace
metadata:
  name: molejo-observability
  labels:
    app.kubernetes.io/part-of: molejo-platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
