apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-agent
  namespace: molejo-observability-agents
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-cluster
  namespace: molejo-observability
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-gateway
  namespace: molejo-observability
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: molejo-otel-agent
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/stats", "namespaces", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: molejo-otel-agent
subjects:
  - kind: ServiceAccount
    name: otel-agent
    namespace: molejo-observability-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: molejo-otel-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: molejo-otel-cluster
rules:
  - apiGroups: [""]
    resources: ["events", "namespaces", "nodes", "pods", "replicationcontrollers", "resourcequotas", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: molejo-otel-cluster
subjects:
  - kind: ServiceAccount
    name: otel-cluster
    namespace: molejo-observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: molejo-otel-cluster
